# Identificador único del proyecto en SonarQube
sonar.projectKey=zenta-template-front-angular-tailwind
sonar.projectVersion=1.0.0

# Código fuente principal
sonar.sources=src

# Excluir archivos generados, pruebas internas o irrelevantes
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts,**/test.ts,**/karma.conf.js,**/environment.*.ts,**/polyfills.ts

# Ruta donde se ubican los archivos de test (usualmente dentro de src)
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Reporte de cobertura generado por Karma + Jasmine + cobertura Istanbul
# Se genera automáticamente cuando ejecutas: npm run test:coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Excluir archivos del cálculo de cobertura (por ejemplo, configuraciones o módulos vacíos)
sonar.coverage.exclusions=**/main.ts,**/polyfills.ts,**/environment.*.ts,**/*.spec.ts,**/*.mock.ts,**/*.d.ts

# Encoding de archivos fuente
sonar.sourceEncoding=UTF-8

# Configuración adicional para TypeScript
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Forzar el proveedor de SCM para obtener la información de "blame"
sonar.scm.provider=git
sonar.projectBaseDir=.
